[package]
name = "otoboke_server"
version = "0.1.0"
authors = ["Iwancof <rock.iwancof@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "0.2"
