[package]
name = "otoboke_server"
version = "0.1.0"
authors = ["Iwancof <rock.iwancof@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "0.2"
serde_json = "1.0"
serde = "1.0"
serde_derive = "1.0"
lazy_static = "1.4.0"
getch = "0.2.1"

